export const ADD_STOCK = 'ADD_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const UPDATE_STOCK = 'UPDATE_STOCK';
export const SET_STOCK_LIST = 'SET_STOCK_LIST';
export const SET_DETAILED_STOCK = 'SET_DETAILED_STOCK';
export const DELETE_DETAILED_STOCK = 'DELETE_DETAILED_STOCK';

export const UPDATE_CURRENCY_LIST = 'UPDATE_CURRENCY_LIST';
export const SET_DETAILED_CURRENCY = 'SET_DETAILED_CURRENCY';
export const DELETE_DETAILED_CURRENCY = 'DELETE_DETAILED_CURRENCY';

export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const DELETE_SEARCH_RESULTS = 'DELETE_SEARCH_RESULTS';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';
export const DELETE_SEARCH_KEYWORD = 'DELETE_SEARCH_KEYWORD';
